### ISSUE TITLE
Simbelmyne running on Winboard

### ISSUE THREAD

**Issue by CPagador** [sroelants/simbelmyne#134]
Hi,

I'd like to include your chess engine on [my tournament](https://talkchess.com/forum3/viewtopic.php?f=6&t=82800), but it just doesn't start on Winboard 4.6.2. You can download the GUI here:

https://www.mediafire.com/file/60w28imp4erc4xc/WinBoard-4.6.2.exe/file

Best regards,
Carlos

**Comment by sroelants** [comment]
Thanks for letting me know! I don't have access to a Windows machine, but I'll try and see what I can find out!

**Comment by CPagador** [comment]
Simbelmyne 1.7 is working now under Winboard 4.6.2, previous versions could not work, you can follow his performance in my tournament [here](https://talkchess.com/forum3/viewtopic.php?t=83865)
