### ISSUE TITLE
arm64 compilation warning

### ISSUE THREAD

**Issue by ArminiusTux** [sroelants/simbelmyne#218]
Dear @sroelants ,

just wanted to let you know about the following compilation warning (Win11 on ARM64):

<img width="666" alt="simbelmyne_compilation_warning" src="https://github.com/sroelants/simbelmyne/assets/44533868/a0ae44a7-eed8-40f0-8daf-5819b206748a">

The resulting executable is fine however and working.

**Comment by sroelants** [comment]
Thanks for reporting, @ArminiusTux. Not sure how that warning snuck through! Shouldn't affect the binary, though, so you should be good. 😃

**Comment by ArminiusTux** [comment]
Indeed v1.8.0 is also compiling and working nicely - you may close this issue then.
